# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi
MANPATH="/usr/local/texlive/current/texmf/doc/man:$MANPATH"
INFOPATH="/usr/local/texlive/current/texmf/doc/info:$INFOPATH"

PATH="/usr/local/texlive/current/bin/x86_64-linux:$PATH"

export "EDITOR=emacsclient -t"
export "VISUAL=emacsclient -c"

#export SSH_ASKPASS=/usr/lib/openssh/gnome-ssh-askpass
eval `keychain --eval --agents ssh,gpg id_rsa 14498E3961F5B64FA7154EAD2A11A5D0370D5DFF`
 
#eval `keychain --quiet --eval --agents ssh id_rsa`
#eval `source ~/.keychain/$HOSTNAME-sh`
#eval `source ~/.keychain/$HOSTNAME-sh-gpg`
