export EDITOR=emacsclient -t
export VISUAL=emacsclient -c

eval `keychain --eval --agents ssh,gpg id_rsa 14498E3961F5B64FA7154EAD2A11A5D0370D5DFF`
#export SSH_ASKPASS=/usr/bin/pinentry
#eval `keychain --quiet --eval --agents ssh id_rsa`
eval `source ~/.keychain/$HOSTNAME-sh`
eval `source ~/.keychain/$HOSTNAME-sh-gpg`
