#~/.config/beets/config.yaml
directory: /var/lib/mpd/music/NAS/Synology/BEETS/

library: /var/lib/mpd/music/NAS/Synology/BEETS/ADMINISTRATION/musiclibrary.blb

ignore: .@eaDir BEETS .* *~

# plugins: fetchart mpdstats import smartplaylist mpdupdate
plugins: fetchart duplicates missing mpdupdate permissions fromfilename

import:
    write: yes
    copy: no
    move: yes
    resume: ask
    #none_rec_action: skip
    log: /var/lib/mpd/music/NAS/Synology/BEETS/ADMINISTRATION/beets-import-fail
    fromfilename: yes
    permissions: yes
    

match:
    max_rec:
        missing_tracks: none

duplicates:
    album: yes
    merge: yes
    # delete: yes

paths:
    #default: $albumartist/$album%aunique{}/$track $title
    default: $albumartist/$album/$track $title
    singleton: Non-Album/$artist/$title
    #comp: Compilations/$album%aunique{}/$track $title
    comp: Compilations/$album/$track $title

mpd:
    host: localhost
    port: 6600

fetchart:
    auto: yes


missing:
    #format: $albumartist - $album - $title
    #format: $albumartist - $album
    count: yes
    total: no

match:
    preferred:
        #countries: ['US', 'GB|UK']
        media: ['CD', 'Digital Media|File']
        original_year: yes

permissions:
    file: 644
    dir: 755
